classifiers_cluster:
    trusted_probability: 0.65
    checks:
      - popularity
      - maintenance
      - maturity
    reversed:
      - stale_branches_count
      - issues_active_percent
      - pr_active_percent
      - issues_actual_count
      - pr_actual_count
      - issues_processed_in_avg
      - pr_processed_in_avg
      - issues_processed_in_median
      - pr_processed_in_median
      - first_issue_date_int
      - first_pr_date_int
    metrics:
      popularity:
        last_year:
          users_creating_issues_count: 3
          users_commenting_issues_count: 3
          users_creating_pr_count: 3
          users_commenting_pr_count: 3
          stargazers_count: 3
          forks_count: 3
          users_involved_count: 3
          users_involved_no_stars_count: 3
          total_downloads_count: 8
          questioner_rep_median: 1
          question_view_sum: 5
          answers_avg: 3
          question_score_sum: 3
          questioners_count: 2
          questions_count: 5
          questions_resolved_percent: 2
        total:
          dependants_count: 6
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          contributors_count: 1
          watchers_count: 1
          forks_count: 1
          users_involved_no_stars_count: 1
          total_downloads_count: 8
          questions_count: 2
          questions_resolved_percent: 1
      maintenance:
        last_year:
          issues_processed_in_avg: 1
          issues_processed_in_median: 1
          issues_closed_percent: 2
          issues_all_count: 2
          pr_processed_in_avg: 1
          pr_processed_in_median: 1
          pr_closed_percent: 2
          pr_all_count: 2
          releases_count: 4
          commits: 4
        total:
          issues_closed_percent: 0.5
          issues_non_owner_percent: 0.5
          issues_with_contrib_comments_percent: 0.5
          issues_all_count: 0.5
          issues_processed_in_avg: 0.25
          issues_processed_in_median: 0.25
          pr_closed_percent: 0.5
          pr_non_owner_percent: 0.5
          pr_with_contrib_comments_percent: 0.5
          pr_all_count: 0.5
          pr_processed_in_avg: 0.25
          pr_processed_in_median: 0.25
          releases_count: 1
          stale_branches_count: 1
          life_period: 1
          last_changed: 1
      maturity:
        last_year:
          users_creating_issues_count: 2
          users_commenting_issues_count: 2
          users_creating_pr_count: 2
          users_commenting_pr_count: 2
          stargazers_count: 2
          forks_count: 2
          users_involved_count: 2
          users_involved_no_stars_count: 2
          total_downloads_count: 2
          question_view_sum: 2
          question_score_sum: 0.5
          questioners_count: 2
          questions_count: 2
          questions_resolved_percent: 0.5
          issues_processed_in_avg: 1
          issues_processed_in_median: 1
          issues_closed_percent: 1
          issues_all_count: 1
          pr_processed_in_avg: 0.5
          pr_processed_in_median: 0.5
          pr_closed_percent: 1
          pr_all_count: 1
          releases_count: 2
          commits: 2
        total:
          dependants_count: 3
          users_creating_issues_count: 1
          users_commenting_issues_count: 1
          users_creating_pr_count: 1
          users_commenting_pr_count: 1
          watchers_count: 1
          forks_count: 1
          users_involved_no_stars_count: 1
          total_downloads_count: 1
          issues_closed_percent: 0.5
          issues_non_owner_percent: 0.5
          issues_with_contrib_comments_percent: 0.5
          issues_all_count: 0.5
          issues_processed_in_avg: 0.5
          pr_closed_percent: 0.5
          pr_non_owner_percent: 0.5
          pr_with_contrib_comments_percent: 0.5
          pr_all_count: 0.5
          pr_processed_in_avg: 0.5
          commits: 1
          releases_count: 1
          stale_branches_count: 1
          life_period: 1
          last_changed: 1
          questions_count: 1
          questions_resolved_percent: 0.5
